extraction:
  cpp:
     prepare:
        packages:
          - libboost-all-dev
          - bison
     configure:
        command:
        - ./bootstrap
        - ./configure --with-modules="" --without-lua
     index:
        build_command:
        - cd source && make -f makefile
